-- Schéma commun à tous les agents de scraping (bobochic, bestmobilier, sweeek, baita, habitat)
-- Exécuter une seule fois dans l'éditeur SQL Supabase

create table if not exists category_snapshots (
  id bigint generated by default as identity primary key,
  site text not null,
  category_name text not null,
  category_url text not null,
  declared_product_count integer,
  scraped_product_count integer not null default 0,
  status text not null,
  error_message text,
  scraped_at timestamptz not null
);

create table if not exists products (
  id bigint generated by default as identity primary key,
  site text not null,
  url text not null,
  name text,
  collection_name text,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz,
  last_price_cents integer,
  last_review_count integer,
  unique (site, url)
);

create table if not exists product_snapshots (
  id bigint generated by default as identity primary key,
  site text not null,
  category_name text not null,
  category_url text not null,
  product_url text not null,
  product_name text not null,
  collection_name text,
  price_cents integer,
  price_text text,
  review_count integer,
  badges text,
  position integer,
  scraped_at timestamptz not null
);

create table if not exists daily_events (
  id bigint generated by default as identity primary key,
  site text not null,
  event_type text not null,
  category_name text,
  product_url text not null,
  product_name text,
  old_value text,
  new_value text,
  detected_at timestamptz not null
);

create index if not exists idx_category_snapshots_scraped_at on category_snapshots (scraped_at desc);
create index if not exists idx_product_snapshots_site_scraped_at on product_snapshots (site, scraped_at desc);
create index if not exists idx_product_snapshots_product_url on product_snapshots (product_url, scraped_at desc);
create index if not exists idx_daily_events_site_detected on daily_events (site, detected_at desc);
create index if not exists idx_daily_events_type on daily_events (event_type, detected_at desc);

-- Lecture publique en lecture seule pour le dashboard (clé anon)
alter table product_snapshots enable row level security;
alter table daily_events enable row level security;
alter table products enable row level security;

create policy "dashboard_read_snapshots" on product_snapshots for select using (true);
create policy "dashboard_read_events" on daily_events for select using (true);
create policy "dashboard_read_products" on products for select using (true);

create or replace view latest_product_snapshots as
select distinct on (site, product_url) *
from product_snapshots
order by site, product_url, scraped_at desc;
